### PR TITLE
Vulnerability merges

### PR DESCRIPTION
**Pull request by adongare**
- Merged two dependabot PRs for Elliptic(upgrade v6.4.1 to v6.5.3) & lodash(upgrade v4.17.14 to v4.17.19)
- Ran `yarn run build-everything`

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository. 
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [ ] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [x] `cql4browsers.js` built with `yarn run build-everything` if coffeescript source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by adongare** [comment]
Hi @cmoesel, when you get a chance can you please take a look at this PR?

**Comment by adongare** [comment]
@cmoesel Sorry to bother you again. We are planning to deploy these security fixes along with some other security fixes in the bonnie. Could you please take a look at this PR?

**Comment by cmoesel** [comment]
Hi @adongare -- I apologize; I was on vacation until August 19th, so I'm playing catchup today.  This is probably fine, but I'll give it a closer look this afternoon.

**Comment by cmoesel** [comment]
@adongare -- it looks like #137 is ready to be merged too.  How would you feel about us merging that today too?  Would that be OK?  If you perceive it as too much risk, we can hold off on it a little longer.

**Comment by adongare** [comment]
@cmoesel No worries, thanks for looking into this. I've not looked into #137. Can we merge security fixes and publish a minor version then merge #137 to publish another version if that works. I'll pull the #137 change in bonnie and run a regression test.

**Comment by cmoesel** [comment]
OK.  This is released in 1.4.4: https://github.com/cqframework/cql-execution/releases/tag/v1.4.4

**Comment by adongare** [comment]
Thanks @cmoesel!
I'll test #137 with bonnie and let you know but you can merge it meanwhile.

**Comment by cmoesel** [comment]
I'll wait.  It would be pretty hard to back this one out if it causes issues w/ Bonnie.

**Pull request merged**
