### PR TITLE
Bonniemat 629-623

### PR DESCRIPTION
**Pull request by adongare**
This PR has fixes for following:

- Allow empty tuples {:}

When bonnie executes the empty tuple, tuple constructor execution fails.
e.g.
 ```
@elements = for el in json.element
      name: el.name
      value: build el.value
```
gets translated to:
```
var i, len, ref1, results;
        ref1 = json.element;  //here ref is null because json.element is not available & ref.length fails
        results = [];
        for (i = 0, len = ref1.length; i < len; i++) {
          el = ref1[i];
          results.push({
            name: el.name,
            value: build(el.value)
          });
        }
```

-  Updated IndexOf execution `.exec` to `.execute`
`.exec` doesn't track values to context object which affects calculation.

original issues: 
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-629
https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-623

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository. 
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [ ] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [x] `cql4browsers.js` built with `yarn run build-everything` if coffeescript source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by cmoesel** [comment]
Hi @adongare -- has this fix been regression-tested on Bonnie?  I haven't fully reviewed it yet, but it would be good to know if it's been regression-tested before I merge.  Wouldn't want to have to back it out if it failed regression.

Also, I didn't even know an empty tuple like that was legal.  Wow!

**Comment by adongare** [comment]
Hi @cmoesel, that's a good point. I've not regression tested it yet. I've tested with couple of measures though. I'll get it regresion tested. Please don't merge it.

Regarding empty tuple- I was not aware of it as well. This is Bryn's suggestion to use empty tuple.
e.g.
```
define function "Encounter Days"(QualifyingEncounter "Encounter, Performed" ):
  ( {:} ) Whiteboard
    let Hospitalization: Global."HospitalizationWithObservation" ( QualifyingEncounter ),
    MeasurementInterval: Interval[start of Hospitalization + 24 hours, Min({ start of Hospitalization + 24 hours + 10 days, 
      end of Hospitalization }
    )]
    return expand { MeasurementInterval } per day 
```

**Comment by cmoesel** [comment]
I only asked about the regression test because someone here said that they thought they *might* remember changing those `exec`s to `execute`s and it causing strange, unexpected issues.  That said, we can't see *why* it would do that -- so it's completely possible it is a phantom recollection and that everything is fine.  Still, probably worth doing a regression!

And that Whiteboard thing is pretty trippy.  I'm gonna have to talk to Bryn about that one!

**Comment by adongare** [comment]
@cmoesel It's not urgent, merging can wait for sometime because we don't want to release this until Annual Update gets over. I'll definitely get this regression tested once our QA gets some bandwidth and let you know about it. Pls let me know about- how does empty tuple discussion with Bryn go. Accordingly, I can revert it or keep. Thanks!

**Comment by cmoesel** [comment]
Thanks for the update.  I'm not suggesting that I'll fight the empty tuple -- I just think it's a really interesting approach and I'd like to understand it better.  If people can write empty tuples then it's good to support it (even if we think it's weird)!

**Comment by adongare** [comment]
HI @cmoesel, this was long pending from my side. Haven't got chance to prioritize this work, since there was workaround provided to users. I've updated this PR with latest master changes. We also regression tested this with bonnie and went well. haven't observed any differences in calculations. Could you please go through this PR again. Thanks!

**Comment by adongare** [comment]
@cmoesel Just following up on this. You might be busy with connectathon. Could you please take a look at this PR when you get chance. Bonnie needs this for upcoming Pre-AU. Thanks!

**Review by cmoesel — APPROVED** [review]
Looks good.  The changes make sense.  The tests pass.  Thanks, @adongare!

**Comment by cmoesel** [comment]
@adongare -- do you need a new official cql-execution release as well?  Are you expecting any more changes?

**Comment by adongare** [comment]
@cmoesel Yeah, new version would be great. We don't expect any more changes as of now.

**Comment by cmoesel** [comment]
@adongare -- Done: https://github.com/cqframework/cql-execution/releases/tag/v1.4.5

Sorry for the delay!

**Comment by adongare** [comment]
No worries. This is perfect timing. We are targeting bonnie release mid next week. Thanks for looking into PR!

**Pull request merged**
