### PR TITLE
Feature/include codesystems

### PR DESCRIPTION
**Pull request by poolis**
I believe the offending CQL is this...

```
...
include Terminology version '1.0.0' called Terminology
...
code "Institutional": 'institutional' from Terminology."claim-type" display 'Institutional'
code "Professional": 'professional' from Terminology."claim-type" display 'Professional'
...
define "Institutional or Professional Claims":
    [Claim: "Institutional"]
        union
        [Claim: "Professional"]
...
```

When the `Library` object is created, the `codesystems` in the included libraries are not in the `codesystems` of the `Library` object, despite the included libraries being in the `includes` parameter.  This causes a lookup failure and processing to error out. With this change, execution seems to continue as expected.

### CODE REVIEW

**Comment by cmoesel** [comment]
Hi @poolis!  Thank you for the contribution.  I apologize; this somehow slipped our radar!

On my first glance, the code looks good!  But... there are a few issues that got hung up in CI:

- `yarn audit`: This one really isn't your fault.  We updated the dependencies today, but you'll have to rebase or merge.
- `cql4browsers`: You can fix this by running `yarn run build:browserify`
- `lint and prettier`: It looks like you formatted using different prettier rules (or a different version of prettier) than we use.  I think if you run `yarn run prettier:fix` it should use our prettier version and rules.

Thanks again!
Chris

**Review by cmoesel — CHANGES_REQUESTED** [review]
Hi @poolis!  Thank you for the contribution.  I apologize; this somehow slipped our radar!

On my first glance, the code looks good!  But... there are a few issues that got hung up in CI:

- `yarn audit`: This one really isn't your fault.  We updated the dependencies today, but you'll have to rebase or merge.
- `cql4browsers`: You can fix this by running `yarn run build:browserify`
- `lint and prettier`: It looks like you formatted using different prettier rules (or a different version of prettier) than we use.  I think if you run `yarn run prettier:fix` it should use our prettier version and rules.

Thanks again!

**Comment by cmoesel** [comment]
It seems prettier is still failing.  Did you run `yarn prettier:fix`?  And if so, did it result in changes?  I just tested this and when I run `prettier:fix` it _does_ result in changes that need to be checked in.

If your branch is setup to allow pushes from writers of the upstream repository, I can push the prettier fixes if you want.  Let me know.

**Comment by poolis** [comment]
@cmoesel When I run `yarn prettier:fix` it does not make any changes.  If you can try pushing the prettier fixes that would be great.  Thanks!

**Comment by cmoesel** [comment]
Thanks, @poolis.  I don't know why that's not working; yarn should be using the `prettier` installed by the `devDependencies` and since we don't have a prettier config, I thought it should be using the default settings...

Git won't let me push to your remote branch:
```
$ git push https://github.com/apervita/cql-execution.git feature/include_codesystems                            ─╯
remote: Permission to apervita/cql-execution.git denied to cmoesel.
fatal: unable to access 'https://github.com/apervita/cql-execution.git/': The requested URL returned error: 403
```

I'll try forking your repo and submitting a PR into your branch so it fixes your PR into our branch.  Crazy!

**Comment by cmoesel** [comment]
See: https://github.com/apervita/cql-execution/pull/1

**Review by cmoesel — APPROVED** [review]
Thanks for this, @poolis!  Sorry for the technical difficulties w/ prettier...

**Pull request merged**
