### PR TITLE
Is operator

### PR DESCRIPTION
**Pull request by losborne**
Implement the `Is` CQL Operator.  This one is a nice-to-have and not required for Bonnie 4.0 release.

To deal with determining the type of non-CQL datatypes at runtime, a function, `getValueType` (named after the variable that is assigned by the `cql-to-elm` translator, is passed into the PatientContext.  `getValueType` acts as an interface for providing the type string to the execution engine.  An example one was added to the test execution context.  The one for Bonnie can be found at https://github.com/projecttacoma/cqm-execution/blob/990a1b56147a23376cb8690bafa35e214997ca60/lib/models/calculator.js#L112

projecttacoma repos all have branches set up to use this named `is-operator` for testing in Bonnie.

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository. 
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [x] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [x] `cql4browsers.js` built with `yarn run build-everything` if coffeescript source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by cmoesel** [comment]
Closing this PR without merging, as another implementation is already under way.

**Comment by psbrandt** [comment]
@cmoesel, is the other implementation available in a branch somewhere?

**Comment by cmoesel** [comment]
@psbrandt -- yes, it is available in the [decaffeinate-2020](https://github.com/cqframework/cql-execution/tree/decaffeinate-2020) branch, which is released as [2.0.0-beta.1](https://github.com/cqframework/cql-execution/releases/tag/2.0.0-beta.1).

If you have your own `PatientSource` implementation, you will need to update it to provide some functions that are needed for the new support if `Is`.  See the 2.0.0-beta.1 release notes (in prior link) for details.  If you're using `cql-exec-fhir`, you'll need to use the [1.5.0-beta.1](https://github.com/cqframework/cql-exec-fhir/releases/tag/v1.5.0-beta.1) release.

**Comment by psbrandt** [comment]
Was just about to post that I found this:

https://github.com/cqframework/cql-execution/blob/f43354d5483aff4a415e2d82c2bfaa2fb498d17a/src/elm/type.js#L493-L518

I will update to the betas of `cql-execution` and `cql-exec-fhir`. Thanks so much!!

**Comment by cmoesel** [comment]
Thanks, @psbrandt.  It is in beta, so we appreciate any feedback you might have.  Note that we bumped to 2.0.0 because it's also a rewrite of the whole library in ES6 JavaScript (it used to be CoffeeScript).  There shouldn't be any regressions, so let us know if you find anything fishy!

**Comment by psbrandt** [comment]
I will absolutely let you know. I'm actually using the [CQL Testing Framework](https://github.com/AHRQ-CDS/CQL-Testing-Framework), so there are plenty of moving parts :).

**Comment by psbrandt** [comment]
Seems to be working (after publishing an [updated CQL Testing Framework](https://www.npmjs.com/package/@phema/cql-testing)).  Went from:
```
  1) 8.cardiac-conduction-qrs_v1.0.0
       001 Case - values in range, no exclusions:
     Error: Unimplemented Expression: Is
```

To:
```
  8.cardiac-conduction-qrs_v1.0.0
    ✓ 001 Case - values in range, no exclusions
```

**Comment by cmoesel** [comment]
Awesome.  Once cql-execution goes out of beta, we'll update cql-testing too.

**Pull request closed without merging**
