### PR TITLE
Bug - fixed wrong check for areNumeric() in union and intersect

### PR DESCRIPTION
**Pull request by fuzzthink**
Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository. 
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [x] All dependent libraries are appropriately updated or have a corresponding PR related to this change

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by cmoesel** [comment]
Thank you for submitting this PR, @fuzzthink!  When we make changes to the coffee source, we also check in the generated `cql4browsers.js` file.  I apologize that this is not documented well, but you'll notice that Travis failed above because cql4browsers is out of sync.

Can you please run `yarn run build-everything` and push up the modified `cql4browsers.js` file to your fork?

**Comment by cmoesel** [comment]
Thanks for updating, @fuzzthink -- and thanks for the README addition as well!

Travis is still failing, but that's due to some transitive dependencies that have recently discovered vulnerabilities.  I already have a PR in that includes a fix for that (#89) -- so once that gets merged we should be fine.  In the mean time, we'll run the tests locally and verify all is well.

**Comment by cmoesel** [comment]
@jbradl11 -- I've run the tests locally and they all pass.  Code looks good as well (minor change).

Does someone from Bonnie need to review this and run it through regression?

**Comment by fuzzthink** [comment]
Added checkbox to PR template for cql4browsers.js.

**Comment by cmoesel** [comment]
Merged.  Thanks @fuzzthink!

**Pull request merged**
