### PR TITLE
Added support for referencing codes in other libraries

### PR DESCRIPTION
**Pull request by jbradl11**
- Added support for allowing codes to be referenced in other libraries. 
- Re-generated the cql4browsers

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1270
- [x] JIRA ticket links to this PR: 
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered.
    * In rare situations, this may not be possible or applicable to a PR. In those situations:
        1. Note why this could not be done or is not applicable here:
        2. Add TODOs in the code noting that it requires a test
        3. Add a JIRA task to add the test and link it here:
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint: N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

### CODE REVIEW

**Comment by cmoesel** [comment]
So.. the code looks good and tests run, but... when I run `cake build-cql4browsers`, it produces different cql4browsers code than is checked in.  @jbradl11, can you double-check that you generated cql4browsers correctly?

**Comment by cmoesel** [comment]
So I forgot you wanted another reviewer on this.  Sorry...

**Comment by jbradl11** [comment]
Can we revert the merge until we have a Bonnie team member fully review it from our perspective?

**Comment by cmoesel** [comment]
Reverting merges isn't very fun and makes the history messy.  How about we don't merge anything else into master until this new code has been reviewed by a Bonnie team member?  If a Bonnie team member has concerns we can address them right away via another PR.  Is that OK?

**Comment by cmoesel** [comment]
Phew!

**Pull request merged**
